### ISSUE TITLE
Canvas is no longer centred on web

### ISSUE THREAD

**Issue by thinknathan** [ts-defold/tsd-template-yagames#42]
This alignment issue is new to me. Something may have changed in the last couple Defold versions.

![Screenshot 2024-06-25 at 7 03 48 PM](https://github.com/ts-defold/tsd-template-yagames/assets/4023542/fd48b78f-22a7-4722-ae9b-315bdd1cbd55)

Tested on Firefox and Chrome, same result.

**Comment by thejustinwalsh** [comment]
I thought I was using a css grid to pull that off?
I also wonder what happened here...?

**Comment by thejustinwalsh** [comment]
It doesn't look like the index.html file has changed much over the last 3 years, so maybe some edge case of styling I was leaning on has been modified in web browsers, and this is the result of some implicit behavior that is no longer valid?

https://github.com/ts-defold/tsd-template-yagames/blame/4d4b7ffc4c402bb4de5ac89e60bb575c2d0acb21/index.html

**Comment by thejustinwalsh** [comment]
Something is now injecting inline styling on the `app-container` element.
<img width="1595" alt="image" src="https://github.com/ts-defold/tsd-template-yagames/assets/72912/cc8d01f1-3a5a-4c4b-9342-c923612b5126">

**Comment by thejustinwalsh** [comment]
@thinknathan I just updated the `game.project` and built it locally, and I do not see this issue.
Tracking down what is different from my local env.

**Comment by thejustinwalsh** [comment]
> @thinknathan I just updated the `game.project` and built it locally, and I do not see this issue. Tracking down what is different from my local env.

Well... I didn't restart Defold to apply the update, and the latest binary adds the extra styles to the canvas element. 😭

**Comment by thejustinwalsh** [comment]
![image](https://github.com/ts-defold/tsd-template-yagames/assets/72912/d23c8bde-9fee-4965-aebc-3486563fe489)

**Comment by thejustinwalsh** [comment]
I think I located the offending changes here: Most of the Scale Modes inject inline styles.
https://github.com/defold/defold/pull/8682/files#diff-b82ef5179fba0dcb45eca1520e9a3f9e0372c4846534e91545ab5a84e5ae7326R987-R1041
